### ISSUE TITLE
🗺 Epic: Path to typescript scaffold-eth with packages eth-hooks, eth-components, eth-contract-warehouse

### ISSUE THREAD

**Issue by ShravanSunder** [scaffold-eth/scaffold-eth-typescript#23]
# Path to npm packages & typescript
This project will be used to coordinate the path to typescript npm packages
- eth-components
- eth-hooks 
- eth-contract-warehouse

# Current Milestones
## eth-components v1
Moving things into library: everything stays the same for max compatibility. use typescript.
- [x] scaffold-eth/eth-components#2
- [x] scaffold-eth/eth-components#6

## eth-hooks v2
Already released, typescript.  continue some basic testing and bug fixes

### Initial changes for context
eth-components v2: a context via react-web3 to pass around the ethers provider
eth-hooks v3:  a context via react-web3 to pass around the ethers provider. Modify tests and add more tests
- [x] scaffold-eth/eth-hooks#50
- [x] #5
- [x] #4 
- [x] #3
- [x] #1
- [x] scaffold-eth/eth-components#9
- [x] scaffold-eth/eth-components#12
- [x] scaffold-eth/eth-components#13

### Unit testing eth-hooks
- [ ] scaffold-eth/eth-hooks#77
- [x] scaffold-eth/eth-components#16
- [x] scaffold-eth/eth-components#14
- [x] scaffold-eth/eth-components#10

### scaffold-eth-typescript context
- [x] #25
